import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

// Product screenshots as content: each entry holds the CURRENT image and
// the recipe that produced it (page, viewport, steps in the body), so a
// stale screenshot is regenerated by following its own documentation
// rather than archaeology. Components render entries via <ProductShot id>.
const screenshots = defineCollection({
  loader: glob({ pattern: '**/*.md', base: './src/content/screenshots' }),
  schema: ({ image }) =>
    z.object({
      title: z.string(),
      alt: z.string(),
      image: image(),
      /** Short mono label shown in the frame bar, e.g. "everwas · overview" */
      frameLabel: z.string(),
      /** Caption rendered under the shot; the marketing claim it supports. */
      caption: z.string(),
      /** Where this was captured (product page/route or external system). */
      source: z.string(),
      viewport: z.object({ width: z.number(), height: z.number() }),
      capturedAt: z.coerce.date(),
    }),
});

export const collections = { screenshots };
