// Package supplicant generates 802.1X client configuration pointing at the
// certificate the agent already holds.
//
// This is the step that is manual in every 802.1X rollout: the certificate
// exists on the machine and something still has to tell the machine to present
// it. The agent is in a position to do both, which is the whole reason it is
// worth doing here.
//
// GENERATING a profile is safe. APPLYING one is not: telling a machine to start
// authenticating on a network that is not expecting it is how a fleet goes
// offline in one push. So this package writes a file and does nothing else. It
// does not start wpa_supplicant, does not reload a running one, and does not
// touch NetworkManager. The apply step is deliberately somebody's explicit
// decision, made once per site, after the profile has been tested against that
// site's own switches.
package supplicant

import (
	"errors"
	"fmt"
	"path/filepath"
	"strings"
)

// Profile is everything a supplicant needs to authenticate as this machine.
type Profile struct {
	// Identity is the EAP identity presented in the handshake. For EAP-TLS the
	// real identity is the certificate, and this is what appears in the RADIUS
	// User-Name, which is what an operator reads in the logs. It should be the
	// device UUID, matching the certificate's Common Name, so a session in the
	// RADIUS log and a device in the console are the same string.
	Identity string

	// CertDir holds network.key, network.crt and network-chain.pem, as written
	// by internal/netcert.
	CertDir string

	// SSID selects a wireless network. Empty means WIRED 802.1X, which is a
	// different key management mode rather than the same thing without a name.
	SSID string
}

// Wired reports whether this profile is for wired 802.1X.
func (p Profile) Wired() bool { return p.SSID == "" }

// ErrInvalidProfile means the profile would produce a config that is wrong or
// unsafe, rather than one that merely fails to authenticate.
var ErrInvalidProfile = errors.New("supplicant: invalid profile")

// Render produces a wpa_supplicant configuration file.
//
// wpa_supplicant's format is unquoted directives at the top level and
// double-quoted strings inside a network block, with no escape mechanism worth
// relying on. A value containing a quote or a newline therefore does not
// produce a broken string, it produces ADDITIONAL DIRECTIVES: an SSID of
//
//	corp"
//	network={ key_mgmt=NONE
//
// would append an open network to the machine's configuration. Every
// interpolated value is validated rather than escaped, because the set of
// values that are legitimate here is small and known, and refusing is a much
// better failure than emitting a config nobody reads before applying.
func Render(p Profile) (string, error) {
	if err := validate(p); err != nil {
		return "", err
	}

	var b strings.Builder
	b.WriteString("# Generated by the OpenRMM agent. Do not edit: it is rewritten\n")
	b.WriteString("# whenever the device's certificate is renewed.\n")
	b.WriteString("#\n")
	b.WriteString("# The private key is NOT in this file. It is referenced by path and\n")
	b.WriteString("# stays owner-only where the agent wrote it.\n\n")

	b.WriteString("ctrl_interface=/run/wpa_supplicant\n")
	// EAPOL version 2 is what every switch made this decade speaks. Some older
	// Cisco gear ignores the field entirely, and nothing in current use
	// requires version 1, so this is the safe default rather than a tuning.
	b.WriteString("eapol_version=2\n")

	if p.Wired() {
		// ap_scan=0 is REQUIRED for wired 802.1X and is the single most common
		// reason a hand-written wired profile silently never authenticates:
		// the default tells wpa_supplicant to scan for access points and pick
		// a network, and on a wired interface it finds none, so it sits there
		// having done nothing wrong and nothing at all.
		b.WriteString("ap_scan=0\n")
	}
	// Skips a full handshake on reassociation. Worth having because the
	// alternative on a flapping link is a full TLS exchange per flap, which is
	// load on the RADIUS server proportional to how bad the cabling is.
	b.WriteString("fast_reauth=1\n\n")

	b.WriteString("network={\n")
	if !p.Wired() {
		fmt.Fprintf(&b, "\tssid=%q\n", p.SSID)
		// WPA-EAP for wireless; wired uses bare IEEE8021X. Using the wireless
		// value on a wired interface fails in a way that reads like a
		// certificate problem, which is a long way from the actual cause.
		b.WriteString("\tkey_mgmt=WPA-EAP\n")
	} else {
		b.WriteString("\tkey_mgmt=IEEE8021X\n")
	}
	b.WriteString("\teap=TLS\n")
	fmt.Fprintf(&b, "\tidentity=%q\n", p.Identity)
	fmt.Fprintf(&b, "\tca_cert=%q\n", filepath.Join(p.CertDir, "network-chain.pem"))
	fmt.Fprintf(&b, "\tclient_cert=%q\n", filepath.Join(p.CertDir, "network.crt"))
	fmt.Fprintf(&b, "\tprivate_key=%q\n", filepath.Join(p.CertDir, "network.key"))
	// No private_key_passwd: the agent generates the key unencrypted and
	// protects it with file permissions, because a passphrase that has to be
	// readable by an unattended supplicant is not a passphrase.
	b.WriteString("}\n")

	return b.String(), nil
}

// validate refuses anything that would change the SHAPE of the config.
func validate(p Profile) error {
	if strings.TrimSpace(p.Identity) == "" {
		return fmt.Errorf("%w: identity is empty, so the RADIUS log would not name the device", ErrInvalidProfile)
	}
	if strings.TrimSpace(p.CertDir) == "" {
		return fmt.Errorf("%w: no certificate directory", ErrInvalidProfile)
	}
	for field, value := range map[string]string{
		"identity": p.Identity,
		"cert dir": p.CertDir,
		"ssid":     p.SSID,
	} {
		if strings.ContainsAny(value, "\"\n\r") {
			return fmt.Errorf(
				"%w: %s contains a quote or newline, which would inject configuration rather than fail",
				ErrInvalidProfile, field)
		}
	}
	return nil
}
